modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="villagelings"
version="1.0.0"
displayName="Villagelings"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="njtur, MCreator"

[[dependencies.villagelings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




